In [ ]:
import pandas as pd
s=pd.Series([10,20,30,40],index=['a','b','c','d'])
print(s)

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
data={'Name':['Ram','Siva','Seetha'],
      'Age':[10,15,9],
      'Marks':[87,91,72]
     }
df=pd.DataFrame(data,index=['a','b','c'])
print(df)

     Name  Age  Marks
a     Ram   10     87
b    Siva   15     91
c  Seetha    9     72

In [43]:
print(df.iloc[2])

Name     Seetha
Age           9
Marks        72
Name: c, dtype: object

In [46]:
print(df.loc['b'])

Name     Siva
Age        15
Marks      91
Name: b, dtype: object

In [ ]:
print(df.head()) # Top 5

     Name  Age  Marks
0     Ram   10     87
1    Siva   15     91
2  Seetha    9     72

In [ ]:
print(df.head(2)) # Top 2

   Name  Age  Marks
0   Ram   10     87
1  Siva   15     91

In [ ]:
print(df.tail()) # last to top 5

     Name  Age  Marks
0     Ram   10     87
1    Siva   15     91
2  Seetha    9     72

In [9]:
print(df.shape)

(3, 3)

In [11]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Marks   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes
None

In [12]:
print(df.describe())

             Age      Marks
count   3.000000   3.000000
mean   11.333333  83.333333
std     3.214550  10.016653
min     9.000000  72.000000
25%     9.500000  79.500000
50%    10.000000  87.000000
75%    12.500000  89.000000
max    15.000000  91.000000

In [13]:
print(df['Name'])

0       Ram
1      Siva
2    Seetha
Name: Name, dtype: object

In [ ]:
print(df[['Name','Marks']])

     Name  Marks
0     Ram     87
1    Siva     91
2  Seetha     72

In [18]:
# Single Row
print(df.iloc[0])

Name     Ram
Age       10
Marks     87
Name: 0, dtype: object

In [17]:
print(df.iloc[0:2])

   Name  Age  Marks
0   Ram   10     87
1  Siva   15     91

In [ ]:
df1=pd.read_csv(r'D:\Codegnan\Skills\Python\Jupyter\Day_33\students.csv')
print(df1)

    ID          Name               Role   Department   Salary    Status
0  101  Aarav Sharma  Software Engineer  Engineering  85000.0    Active
1  102   Priya Patel       Data Analyst    Analytics  72000.0    Active
2  103   Rohan Verma                NaN      Product  95000.0    Active
3  104   Ananya Iyer        UX Designer       Design  78000.0    Active
4  105  Vikram Singh        DevOps Lead  Engineering      NaN  Inactive

In [ ]:
df1=pd.read_csv('students.csv')
print(df1)

    ID          Name               Role   Department   Salary    Status
0  101  Aarav Sharma  Software Engineer  Engineering  85000.0    Active
1  102   Priya Patel       Data Analyst    Analytics  72000.0    Active
2  103   Rohan Verma                NaN      Product  95000.0    Active
3  104   Ananya Iyer        UX Designer       Design  78000.0    Active
4  105  Vikram Singh        DevOps Lead  Engineering      NaN  Inactive

In [22]:
df1.isna()

      ID   Name   Role  Department  Salary  Status
0  False  False  False       False   False   False
1  False  False  False       False   False   False
2  False  False   True       False   False   False
3  False  False  False       False   False   False
4  False  False  False       False    True   False

In [47]:
df1.isnull()

      ID   Name   Role  Department  Salary  Status
0  False  False  False       False   False   False
1  False  False  False       False   False   False
2  False  False   True       False   False   False
3  False  False  False       False   False   False
4  False  False  False       False    True   False

In [23]:
df1.isna().sum()

ID            0
Name          0
Role          1
Department    0
Salary        1
Status        0
dtype: int64

In [48]:
df1.isnull().sum()

ID            0
Name          0
Role          1
Department    0
Salary        1
Status        0
dtype: int64

In [24]:
df1.fillna(0)

    ID          Name               Role   Department   Salary    Status
0  101  Aarav Sharma  Software Engineer  Engineering  85000.0    Active
1  102   Priya Patel       Data Analyst    Analytics  72000.0    Active
2  103   Rohan Verma                  0      Product  95000.0    Active
3  104   Ananya Iyer        UX Designer       Design  78000.0    Active
4  105  Vikram Singh        DevOps Lead  Engineering      0.0  Inactive

In [ ]:
df1['Role']=df1['Role'].fillna(0)

In [53]:
df1.isna().sum()

ID            0
Name          0
Role          0
Department    0
Salary        1
Status        0
dtype: int64

In [ ]:
df1=df1.fillna(0)

In [56]:
df1.isna().sum()

ID            0
Name          0
Role          0
Department    0
Salary        0
Status        0
dtype: int64

In [ ]:
# df1=df1.dropna() # NaN rows will be dropped
df1=df1.drop(2)
print(df1)

    ID          Name               Role   Department   Salary    Status
0  101  Aarav Sharma  Software Engineer  Engineering  85000.0    Active
1  102   Priya Patel       Data Analyst    Analytics  72000.0    Active
3  104   Ananya Iyer        UX Designer       Design  78000.0    Active
4  105  Vikram Singh        DevOps Lead  Engineering      0.0  Inactive

In [57]:
print(df1.duplicated())

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [29]:
print(df1.head())

    ID          Name               Role   Department   Salary    Status
0  101  Aarav Sharma  Software Engineer  Engineering  85000.0    Active
1  102   Priya Patel       Data Analyst    Analytics  72000.0    Active
3  104   Ananya Iyer        UX Designer       Design  78000.0    Active
4  105  Vikram Singh        DevOps Lead  Engineering      0.0  Inactive

In [31]:
print(df1.tail())

    ID          Name               Role   Department   Salary    Status
0  101  Aarav Sharma  Software Engineer  Engineering  85000.0    Active
1  102   Priya Patel       Data Analyst    Analytics  72000.0    Active
3  104   Ananya Iyer        UX Designer       Design  78000.0    Active
4  105  Vikram Singh        DevOps Lead  Engineering      0.0  Inactive

In [32]:
print(df1.shape)

(4, 6)

In [33]:
print(df1.columns)

Index(['ID', 'Name', 'Role', 'Department', 'Salary', 'Status'], dtype='object')

In [35]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 4
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          4 non-null      int64
 1   Name        4 non-null      object
 2   Role        4 non-null      object
 3   Department  4 non-null      object
 4   Salary      4 non-null      float64
 5   Status      4 non-null      object
dtypes: float64(1), int64(1), object(4)
memory usage: 224.0+ bytes
None

In [36]:
print(df1.info)

<bound method DataFrame.info of     ID          Name               Role   Department   Salary    Status
0  101  Aarav Sharma  Software Engineer  Engineering  85000.0    Active
1  102   Priya Patel       Data Analyst    Analytics  72000.0    Active
3  104   Ananya Iyer        UX Designer       Design  78000.0    Active
4  105  Vikram Singh        DevOps Lead  Engineering      0.0  Inactive>

In [37]:
df1.iloc[4]

ID                     105
Name          Vikram Singh
Role           DevOps Lead
Department     Engineering
Salary                 0.0
Status            Inactive
Name: 4, dtype: object