In [1]:
import pandas as pd
s=pd.Series([10,20,30,40],index=['a','b','c','d'])
print(s)

a    10
b    20
c    30
d    40
dtype: int64

In [2]:
data={'Name':['Ram','Siva','Seetha'],
      'Age':[10,15,9],
      'Marks':[87,91,72]
     }
df=pd.DataFrame(data)
print(df)

     Name  Age  Marks
0     Ram   10     87
1    Siva   15     91
2  Seetha    9     72

In [12]:
df1=pd.read_csv(r'D:\Codegnan\Skills\Python\Jupyter\Day_33\students.csv')
print(df1)

    ID          Name               Role   Department   Salary    Status
0  101  Aarav Sharma  Software Engineer  Engineering  85000.0    Active
1  102   Priya Patel       Data Analyst    Analytics  72000.0    Active
2  103   Rohan Verma                NaN      Product  95000.0    Active
3  104   Ananya Iyer        UX Designer       Design  78000.0    Active
4  105  Vikram Singh        DevOps Lead  Engineering      NaN  Inactive

In [13]:
df1=pd.read_csv('students.csv')
print(df1)

    ID          Name               Role   Department   Salary    Status
0  101  Aarav Sharma  Software Engineer  Engineering  85000.0    Active
1  102   Priya Patel       Data Analyst    Analytics  72000.0    Active
2  103   Rohan Verma                NaN      Product  95000.0    Active
3  104   Ananya Iyer        UX Designer       Design  78000.0    Active
4  105  Vikram Singh        DevOps Lead  Engineering      NaN  Inactive

In [14]:
df1.isna()

      ID   Name   Role  Department  Salary  Status
0  False  False  False       False   False   False
1  False  False  False       False   False   False
2  False  False   True       False   False   False
3  False  False  False       False   False   False
4  False  False  False       False    True   False

In [15]:
df1.isna().sum()

ID            0
Name          0
Role          1
Department    0
Salary        1
Status        0
dtype: int64

In [22]:
df1.fillna(0)

    ID          Name               Role   Department   Salary    Status
0  101  Aarav Sharma  Software Engineer  Engineering  85000.0    Active
1  102   Priya Patel       Data Analyst    Analytics  72000.0    Active
2  103   Rohan Verma                  0      Product  95000.0    Active
3  104   Ananya Iyer        UX Designer       Design  78000.0    Active
4  105  Vikram Singh        DevOps Lead  Engineering      0.0  Inactive

In [23]:
df1=df1.fillna(0)

In [24]:
df1.isna().sum()

ID            0
Name          0
Role          0
Department    0
Salary        0
Status        0
dtype: int64

In [32]:
# df1=df1.dropna() # NaN rows will be dropped
df1=df1.drop(2)
print(df1)

    ID          Name               Role   Department   Salary    Status
0  101  Aarav Sharma  Software Engineer  Engineering  85000.0    Active
1  102   Priya Patel       Data Analyst    Analytics  72000.0    Active
3  104   Ananya Iyer        UX Designer       Design  78000.0    Active
4  105  Vikram Singh        DevOps Lead  Engineering      0.0  Inactive